# example docker-compose file
version: '3'
services:
  lcdd:
    image: ibhde/lcdproc
    volumes:
      - /path/to/conf/LCDd.conf:/etc/LCDd.conf:ro
    ports:
      - 13666:13666
    privileged: true
    restart: always

  lcdproc:
    image: ibhde/lcdproc
    command: [ "lcdproc", "-s", "lcdd", "-f", "-c", "/etc/lcdproc.conf", "L" ]
    hostname: myhostname
    volumes:
      - /path/to/conf/lcdproc.conf:/etc/lcdproc.conf:ro
    restart: always
    depends_on:
      - lcdd
